CATEGORY_EXAMPLES = {
    "FRUITS_VEGETABLES": [
        "plátano",
        "manzana",
        "naranja",
        "pera",
        "fresa",
        "tomate",
        "lechuga",
        "brócoli",
        "patata",
        "cebolla",
        "zanahoria",
        "pimiento",
        "calabacín",
        "berenjena",
        "espinacas",
    ],

    "MEAT": [
    "pollo",
    "pechuga de pollo",
    "pechuga",
    "filete de pollo",
    "filete de pechuga",
    "filete de pechuga de pollo",
    "carne de ternera",
    "carne de cerdo",
    "carne picada",
    "filete de ternera",
    "filete de cerdo",
    "chuleta de cerdo",
    "jamón cocido",
    "jamón serrano",
    "jamón ibérico",
    "jamón",
    "chorizo",
    "salchichas",
    "hamburguesa de carne",
    ],

    "FISH_SEAFOOD": [
        "salmón",
        "atún",
        "merluza",
        "bacalao",
        "sardinas",
        "gambas",
        "langostinos",
        "mejillones",
        "calamares",
        "pescado",
        "marisco",
    ],

    "DAIRY_EGGS": [
        "leche entera",
        "leche desnatada",
        "leche semidesnatada",
        "yogur natural",
        "yogur de fresa",
        "queso",
        "queso manchego",
        "mantequilla",
        "nata",
        "crema",
        "huevos",
    ],

    "BAKERY": [
        "pan",
        "barra de pan",
        "baguette",
        "pan de molde",
        "pan integral",
        "croissant",
        "magdalena",
        "bollería",
        "pastel",
        "tarta",
    ],

    "PASTA_RICE_GRAINS": [
    "arroz",
    "arroz blanco",
    "arroz integral",
    "arroz cocido",
    "arroz preparado",
    "arroz largo",
    "arroz basmati",
    "pasta",
    "macarrones",
    "espaguetis",
    "tallarines",
    "fideos",
    "harina",
    "harina de trigo",
    "avena",
    "copos de avena",
    "cereales",
    "quinoa",
    "cuscús",
    "semillas de chía",
    "chía",
    ],

    "CANNED_PACKAGED": [
        "atún en conserva",
        "maíz en conserva",
        "tomate triturado",
        "garbanzos en conserva",
        "lentejas en conserva",
        "sopa",
        "caldo de pollo",
        "caldo de verduras",
        "salsa de tomate",
        "tofu",
        "comida preparada",
    ],

    "SNACKS": [
        "patatas fritas",
        "chips",
        "galletas",
        "chocolate",
        "caramelos",
        "golosinas",
        "frutos secos",
        "almendras",
        "barritas",
        "aperitivo",
    ],

    "BEVERAGES": [
        "agua mineral",
        "agua embotellada",
        "refresco",
        "zumo de naranja",
        "zumo",
        "bebida de soja",
        "bebida de avena",
        "bebida vegetal",
        "café",
        "té",
        "té matcha",
        "infusión",
        "bebida energética",
    ],
    
    "ALCOHOL": [
    "cerveza",
    "cerveza sin alcohol",
    "vino",
    "vino tinto",
    "vino blanco",
    "vino rosado",
    "sidra",
    "cava",
    "champán",
    "whisky",
    "ron",
    "vodka",
    "ginebra",
    ],

    "FROZEN": [
        "verduras congeladas",
        "pescado congelado",
        "carne congelada",
        "pizza congelada",
        "patatas congeladas",
        "helado",
        "plato preparado congelado",
    ],

"HOUSEHOLD_CLEANING": [
    "detergente",
    "detergente para ropa",
    "detergente lavadora",
    "suavizante",
    "suavizante para ropa",
    "suavizante azul",
    "lavavajillas",
    "jabón para platos",
    "lejía",
    "limpiador",
    "limpiador de superficies",
    "limpiador multiusos",
    "productos de limpieza",
    "bolsas de basura",
    "bolsa de basura",
    "bolsas basura",
    "bolsa basura",
    "bolsas para basura",
    "bolsas de basura extra",
    "bolsa de basura extra",
    "esponja",
    "bayeta",
    ],

    "PERSONAL_CARE": [
        "papel higiénico",
        "pañuelos",
        "champú",
        "gel de ducha",
        "jabón",
        "pasta de dientes",
        "cepillo de dientes",
        "desodorante",
        "crema corporal",
        "cosméticos",
    ],

    "PET_SUPPLIES": [
        "comida para perros",
        "comida para gatos",
        "pienso para perros",
        "pienso para gatos",
        "comida húmeda para gatos",
        "premios para perros",
        "arena para gatos",
        "champú para mascotas",
    ],

    "OTHER": [
        "producto desconocido",
        "artículo desconocido",
    ]
}